---

- name: "Remove Android SDK directory"
  file:
    path: "{{ android_sdk_path }}"
    state: absent
    owner: "{{ user }}"
    group: "{{ group }}"

- name: "Create Android SDK directory on {{ android_sdk_path }}"
  file:
    path: "{{ android_sdk_path }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
    recurse: yes

- name: "Download Android SDK {{ android_sdk_download_url }}"
  get_url:
    url: "{{ android_sdk_download_url }}"
    dest: "{{ android_sdk_path }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: a+x

- name: "Extracte Android SDK"
  unarchive:
    src: "{{ android_sdk_path }}/{{ android_sdk_full_file_name }}"
    dest: "{{ android_sdk_path }}"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: change_sdk_dir_name
  shell: "mv {{ android_sdk_path }}/android-sdk-linux/* {{ android_sdk_path }}/"
  changed_when: false

- name: "Remove Android SDK tar file {{ android_sdk_path }}/{{ android_sdk_full_file_name }}"
  file:
    path: "{{ android_sdk_path }}/{{ android_sdk_full_file_name }}"
    state: absent
    owner: "{{ user }}"
    group: "{{ group }}"
  when: remove_lefovers

- name: "Remove Android SDK temp directory"
  file:
    path: "{{ android_sdk_path }}/android-sdk-linux"
    state: absent
    owner: "{{ user }}"
    group: "{{ group }}"

- name: "Create symbolik link from /home/{{ user }}/sdk to {{ android_sdk_path }}"
  file:
    src: "{{ android_sdk_path }}"
    dest: /home/{{ user }}/sdk
    state: link
    owner: "{{ user }}"
    group: "{{ group }}"
