---

- name: "Print ansible_distribution"
  debug:
    msg: "Running os family: {{ ansible_os_family }}"

- name: "Add Gradle repository to apt sources"
  apt_repository:
    repo: "{{ gradle_apt_repository }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: "Update APT package cache"
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: "Install Gradle using apt"
  apt:
    name: gradle
    install_recommends: yes
  when: ansible_os_family == 'Debian'

- name: "Add Gradle repository to yum sources"
  yum_repository:
    name: gradle
    baseurl: "{{ gradle_yum_repository }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: "Install Gradle using yum"
  yum:
    name: "gradle"
  when: ansible_os_family == 'RedHat'
