---


- name: "Create Android NDK directory on {{ android_apk_tool_path }}"
  file:
    path: "{{ android_apk_tool_path }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
    recurse: yes


- name: "Download APK-Tool {{ android_apk_tool_download_url }}"
  get_url: 
    url: "{{ android_apk_tool_download_url }}"
    dest: "{{ android_apk_tool_path }}/apktool.jar"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: a+x



- name: "Download APK-Tool wrapper script {{ android_apk_tool_wrapper_script_download_url }}"
  get_url: 
    url: "{{ android_apk_tool_wrapper_script_download_url }}"
    dest: "{{ android_apk_tool_path }}/apktool"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: a+x



- name: "Create symbolik link from /home/{{ user }}/apktool to {{ android_apk_tool_path }}"
  file: 
    src: "{{ android_apk_tool_path }}"
    dest: /home/{{ user }}/apktool
    state: link 
    owner: "{{ user }}"
    group: "{{ group }}"


