---
- hosts: new_build_agents
  sudo : true
  tasks:

  - name: Create Bamboo-Home directory /usr/lib/android/bamboo
    file: path=/usr/lib/android/bamboo state=directory owner=builder group=builder mode=0755

  - name: Create Installation directory /usr/lib/android/bamboo/installation
    file: path=/usr/lib/android/bamboo/installation state=directory owner=builder group=builder mode=0755

  - name: Copy bamboo.zip from ~/bamboo.zip
    copy: 'src=~/bamboo.zip dest=/usr/lib/android/bamboo/installation/bamboo.zip owner=builder group=builder'

  - name: Extracting bamboo.zip to /usr/lib/android/bamboo/installation
    unarchive: src=/usr/lib/android/bamboo/installation/bamboo.zip dest=/usr/lib/android/bamboo/installation/ copy=no

  - name: Removing bamboo.zip
    shell: "rm -rf /usr/lib/android/bamboo/installation/bamboo.zip"

  - name: Install avg_root.cer keystore for Java
    shell: "keytool -import -trustcacerts -storepass changeit -noprompt -alias avgroot -file /usr/lib/android/bamboo/installation/avg_root.cer -keystore /usr/lib/jvm/java-8-oracle/jre/lib/security/cacerts"
    ignore_errors: yes

  - name: Install avg_issuing.cer keystore for Java
    shell: "keytool -import -trustcacerts -storepass changeit -noprompt -alias avgissuing -file /usr/lib/android/bamboo/installation/avg_issuing.cer -keystore /usr/lib/jvm/java-8-oracle/jre/lib/security/cacerts"
    ignore_errors: yes

  - name: Print AVG's certs.
    shell: "keytool -list -v -storepass changeit -noprompt -keystore /usr/lib/jvm/java-8-oracle/jre/lib/security/cacerts | grep avg"
    register: out
  - debug: var=out.stdout_lines

# # # # not ready yet # # # # - Should stop after when installation donw. (stop)
#  - name: Install bamboo agent.
#    shell: "java -Dbamboo.home=/usr/lib/android/bamboo -jar /usr/lib/android/bamboo/installation/atlassian-bamboo-agent-installer-5.6.2.jar https://atom.cz.avg.com/bamboo/agentServer/"
#    ignore_errors: yes
#    register: out
#  - debug: var=out.stdout_lines

  - name: Start bamboo agent.
    shell: "/usr/lib/android/bamboo/bin/./bamboo-agent.sh start"
    register: out
  - debug: var=out.stdout_lines

  - name: Create symbolik link from /home/builder/bamboo to /usr/lib/android/bamboo/
    file: src=/usr/lib/android/bamboo dest=/home/builder/bamboo state=link owner=builder group=builder