---
- hosts: new_build_agents
  tasks:

  - name: "Download Android NDK"
    get_url: url=http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86_64.bin dest=/usr/lib/android
    register: ndk_file

  - name: "chmod for Android NDK bin file"
    command: chmod a+x {{ndk_file.dest}}

  - name: Execute Android NDK bin file
    command: /usr/lib/android/./android-ndk-r10d-linux-x86_64.bin

  - name: Rename Android NDK directory
    command: mv /home/builder/android-ndk-r10d /usr/lib/android/ndk

  - name: Removing Android NDK tar file
    shell: "rm -rf {{ndk_file.dest}}"

  - name: Create symbolik link from /home/builder/ndk to /usr/lib/android/ndk/
    file: src=/usr/lib/android/ndk dest=/home/builder/ndk state=link owner=builder group=builder
