---
- hosts: new_build_agents
  gather_facts: smart
  sudo : true
  tasks:

  - name: Create /media/outputs directory if not exists
    action: file path=/media/outputs state=directory owner=builder group=builder mode=0755 recurse=yes

  - name: Mount nereus.il.avg.com/firma/outputs to /media/outputs
    shell: "echo '//nereus.il.avg.com/outputs /media/outputs cifs defaults,uid=1000,gid=1000,credentials=/home/builder/.nereuscredentials,iocharset=utf8,sec=ntlm 0 0' >> /etc/fstab"

  - name: Mount -a
    shell: mount -a

  - name: Create symbolik link from /media/outputs to /usr/lib/android/outputs/
    file: src=/media/outputs dest=/home/builder/outputs state=link owner=builder group=builder
    ignore_errors: True
